# Generated by Django 5.2.8 on 2026-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendance_session_attendancesession_anchor_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Used to block buddy punching', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scanned_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scanned_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scanned_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session')},
        ),
    ]
