# ============================================================
# PROJECT CONFIGURATION FILE - beqr/settings.py
# ============================================================
#
# Django project settings for BeQr Attendance System.
# This file contains all project-wide configuration including:
# - Database connection settings
# - Installed apps and middleware
# - Static and media file handling
# - Security settings
# - Authentication configuration
#
# ⚠️  IMPORTANT FOR PRODUCTION:
# - Change SECRET_KEY to a secure random string
# - Set DEBUG = False
# - Set ALLOWED_HOSTS to specific domain names
# - Move database credentials to environment variables

"""
Django settings for beqr project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import dj_database_url
import os
# ============================================================
# 1. BASE DIRECTORY CONFIGURATION
# ============================================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # Absolute path to the project directory: /Users/SagarMaru/Desktop/Attendance-System/BeQr-Attendance System


# ============================================================
# 2. SECURITY SETTINGS (Quick-start development settings)
# ============================================================
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Used for cryptographic signing (sessions, CSRF tokens, etc.)
# In production: move to environment variable and use a secure random key
SECRET_KEY = '14k@@*s5@$1=defyh35z^f8&l_%=ekg9&#7d@3c7msu40%*fn1'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True: Shows detailed error pages with sensitive information
# DEBUG = False: Shows generic error pages (required for production)
DEBUG = False

# List of hosts/domains where the app can run
# '*' allows all hosts (development only!)
# In production: set to specific domain names ['example.com', 'www.example.com']
ALLOWED_HOSTS = ['*']


# When DEBUG=False, Django will only allow requests from hosts in this list.
# In development, we can allow all hosts with ALLOWED_HOSTS = ['*'], but in production, you should specify your domain(s) here.
# For example, if your site is hosted at 'www.beqr.com', you would set:
# ALLOWED_HOSTS = ['www.beqr.com', 'beqr.com']
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app'
]


# ============================================================
# 3. APPLICATION CONFIGURATION
# ============================================================

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',          # /admin/
    'django.contrib.auth',           # User authentication system
    'django.contrib.contenttypes',   # Content type framework
    'django.contrib.sessions',       # Session management
    'django.contrib.messages',       # Messaging framework
    'django.contrib.staticfiles',    # Static file management
    
    # Project apps
    'core',                          # Our custom BeQr app (models, views, etc.)
]

# Middleware: processes requests/responses in order (top to bottom for request, reverse for response)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Enables static file serving on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration (where Django looks for URL patterns)
ROOT_URLCONF = 'beqr.urls'

# Use custom user model instead of default Django User
# CustomUser extends the default User to add extra fields like roll_number
AUTH_USER_MODEL = 'core.CustomUser'


# ============================================================
# 4. TEMPLATE CONFIGURATION
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # Directories to look for templates (in addition to app-specific template folders)
        'DIRS': [],  # Currently empty; templates are in core/templates/
        
        'APP_DIRS': True,  # Look for templates in <app>/templates/ directories
        
        'OPTIONS': {
            # Built-in template variables available in every template
            'context_processors': [
                'django.template.context_processors.request',     # 'request' variable
                'django.contrib.auth.context_processors.auth',    # 'user' and 'perms' variables
                'django.contrib.messages.context_processors.messages', # 'messages' variable
            ],
        },
    },
]

# Web Server Gateway Interface application (used by production servers)
WSGI_APPLICATION = 'beqr.wsgi.application'


import os
import dj_database_url

# ============================================================
# DATABASE CONFIGURATION
# ============================================================
DATABASE_URL = os.environ.get('mysql://avnadmin:AVNS_pwJCKdaqzmgV4iYyscc@mysql-sgr-2434f944-sagarmaru-7cf6.j.aivencloud.com:19216/defaultdb?ssl-mode=REQUIRED')

if DATABASE_URL:
    # Production: Connect to Aiven MySQL via DATABASE_URL environment variable
    # Remove ssl-mode parameter if present (not recognized by mysqlclient)
    db_url = DATABASE_URL.replace('?ssl-mode=REQUIRED', '')
    
    db_config = dj_database_url.parse(db_url)
    
    # Add SSL configuration for mysqlclient
    db_config['OPTIONS'] = {
        'ssl': {
            'ca': '/etc/ssl/certs/ca-certificates.crt',
        }
    }
    
    DATABASES = {
        'default': db_config
    }
else:
    # Development/Build: Use SQLite as fallback (no external DB needed)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
        
        # GRANT PERMISSIONS:
        # GRANT ALL PRIVILEGES ON beqr_db.* TO 'bqr'@'127.0.0.1';
        # FLUSH PRIVILEGES;


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


# ============================================================
# 6. PASSWORD VALIDATION
# ============================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Check password isn't similar to user attributes (username, email, etc.)
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    
    # Check password meets minimum length (default: 8 characters)
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    
    # Check password isn't in list of common passwords
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    
    # Check password doesn't consist entirely of numeric characters
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# 7. INTERNATIONALIZATION (i18n)
# ============================================================
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Language for the interface (English)
LANGUAGE_CODE = 'en-us'

# Timezone for storing/displaying dates (India Standard Time)
TIME_ZONE = 'Asia/Kolkata'

# Enable internationalization (multi-language support)
USE_I18N = True

# Use timezone-aware datetime objects
USE_TZ = True


# ============================================================
# 8. STATIC FILES (CSS, JavaScript, Images)
# ============================================================
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL path to static files in development
# Access static file like: /static/css/style.css
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directory (-ies) containing static files to serve
# When accessing http://localhost:8000/static/css/style.css
# Django looks in: BASE_DIR/static/css/style.css
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Project-wide static files
]

# In production: Run `python manage.py collectstatic` to collect all static files here
STATIC_ROOT = BASE_DIR / 'staticfiles'  # (Currently commented out - uncomment for production)

# ============================================================
# 9. MEDIA FILES (User-Uploaded Content)
# ============================================================

# URL path to access uploaded media (QR codes, etc.)
# Access uploaded QR like: /media/qr_codes/123abc.png
MEDIA_URL = '/media/'

# Directory where uploaded files are stored
# QR codes saved to: BASE_DIR/media/qr_codes/
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# 10. DATABASE & ORM SETTINGS
# ============================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Default primary key field type for models (64-bit integer)
# Auto-incremented ID field: id = models.BigAutoField(primary_key=True)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
